### ISSUE TITLE
Can't run app with Passenger server (Cluster conflict)

### ISSUE THREAD

**Issue by PawelGIX** [adonisjs/adonis-framework#1032]
Can I remove Cluster dependencies in some way?

## Problem
The Phusion Passenger application server tried to start the web application through a Passenger-internal helper tool called the "wrapper". But Passenger was unable to execute that helper tool because it encountered an internal error.

The stdout/stderr output of the subprocess so far is:
```

127.0.0.1
Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
    at Module.require (/usr/local/lib/ruby/gems/2.4/gems/passenger-5.3.4/src/helper-scripts/node-loader.js:63:12)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/home/Cworkshop/domains/ub.cworkshop.usermd.net/public_nodejs/node_modules/@adonisjs/websocket/src/ClusterHop/index.js:12:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at Module.require (/usr/local/lib/ruby/gems/2.4/gems/passenger-5.3.4/src/helper-scripts/node-loader.js:80:25)
[32minfo[39m: serving app on http://127.0.0.1:3000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EPERM 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)e correct repo.
```

## Package version
"@adonisjs/websocket": "^1.0.11",

## Node.js and npm version
node 8.9.3
npm 5.5.1

## Sample Code (to reproduce the issue)
Example server from docs:

```
const { Ignitor } = require('@adonisjs/ignitor')

new Ignitor(require('@adonisjs/fold'))
   .appRoot(__dirname)
   .wsServer()
   .fireHttpServer()
   .catch(console.error)

```

**Comment by RomainLanz** [comment]
Hey @PawelGIX! 👋 

No, there's no way to remove this require.
Since it's not related to Adonis directly I'm closing this issue.
