### ISSUE TITLE
Seeder failing when doing multiple assertion

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [adonisjs/adonis-framework#1066]
Hi, I'm trying to create a seeder for my users, but when I try to load too much element at once it returns me an error (for example I don't have any problems with 10).
```warning:
  WARNING: Adonis has detected an unhandled promise rejection, which may cause undesired behavior in production.
  To stop this warning, use catch() on promises or wrap await
  calls inside try/catch.

Error: aborted
    at PendingOperation.abort (C:\laragon\www\nodejs\adonis-api\node_modules\tarn\lib\PendingOperation.js:23:21)
    at Promise.all.pendingAcquires.map.acquire (C:\laragon\www\nodejs\adonis-api\node_modules\tarn\lib\Pool.js:138:25)
    at Array.map (<anonymous>)
    at utils_1.reflect.Promise.all.then.then (C:\laragon\www\nodejs\adonis-api\node_modules\tarn\lib\Pool.js:137:53)
```

Here is my run method 
```
async run () {
        const users = await Factory.model('App/Models/User').createMany(20)
        users.forEach(async user => {
            try {
                const profile = await Factory.model('App/Models/Profile').make()
                await user.profile().save(profile)
                await Database.close()
            } catch (e) {
                throw (e)
            }
        })
    }
```
I read the documentation but could not find anything related to a seeder failing when 20+ assertions are made. The problem is related to my Database.close(), but if I'm not using it, the command is stuck.

**Comment by jayrchamp** [comment]
@Cedric-Lefebvre Try to move `await Database.close()` outside of the `foreach` loop.

```js
async run () {
    try {
        const users = await Factory.model('App/Models/User').createMany(20)
        users.forEach(async user => {
            const profile = await Factory.model('App/Models/Profile').make()
            await user.profile().save(profile)
        })
        await Database.close()
    } catch (e) {
        throw (e)
    }
}
```

**Comment by Cedric-Lefebvre** [comment]
@jayrchamp Hi, thanks for your answer. 
I tried this solution, and the command gets stuck and doesn't quit if I don't have this Database.close() in the foreach.

**Comment by jayrchamp** [comment]
@Cedric-Lefebvre A forEach loop with async/await will not wait until all items are finished. It will just run tasks and go next. To wait the result you can use “for-in loop”. The seeder command will also exit normally after all tasks have finished.

```js
  async run () {
    try {
      const users = await Factory.model('App/Models/User').createMany(40)

      for (const i in users) {
        const token = await Factory.model('App/Models/Token').make()
        const user = users[i];
        await user.tokens().save(token)
      }

    } catch (e) {
        throw (e)
    }
  }
```

**Comment by Cedric-Lefebvre** [comment]
@jayrchamp Thanks a lot for your help, I learned something new today!
