### ISSUE TITLE
Add Delay in Tests

### ISSUE THREAD

**Issue by codekeyz** [adonisjs/adonis-framework#1070]
I want to add a delay for x-seconds before i proceed to do something. This is currently the code i have, but the `setTimeout-block` doesn't seem to run. 
```javascript
test('Ensure refresh-token works', async ({ client, assert }) => {

  let profResponse = await client
    .get('/users/me')
    .header('accept', 'application/json')
    .header('Authorization', `Bearer ${token}`)
    .send()
    .end();

  // This block doesn't run 
  setTimeout (() => {

    console.log(profResponse.body);

  }, 5000);

});
```

**Comment by thetutlage** [comment]
This doesn't work, since the `setTimeout` doesn't block the function scope. You need to learn about async code and timers in general.

However, what you can do is following.

## Create a separate sleep function
```js
function sleep (time) {
  return new Promise((resolve) => setTimeout(resolve, time))
}
```

and then use it as follows.

```js
await sleep(5000)
```

**Comment by codekeyz** [comment]
@thetutlage  I have updated my code to this

```javascript
test('Ensure refresh-token works', async ({ client, assert }) => {

  let profResponse = await client
    .get('/users/me')
    .header('accept', 'application/json')
    .header('Authorization', `Bearer ${token}`)
    .send()
    .end();

  await sleep(5000)

  console.log(profResponse.body);


});

function sleep (time) {
  return new Promise((resolve) => setTimeout(resolve, time))
}

```

The `await sleep(5000)` works fine now but it's throwing an error on test completion

```bash
 ERRORS 

  1. Ensure refresh-token works
  Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at Test._parseError (/home/XXX/XXX/node_modules/japa/src/Test.js:109:16)
    at Callable.args.run.then.then.catch (/home/XXX/XXX/node_modules/japa/src/Test.js:195:21)
```

**Comment by RomainLanz** [comment]
You need to increase the timeout of your test, by default Japa will wait 2000ms.

https://github.com/thetutlage/japa#test-timeouts

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
