### ISSUE TITLE
Application crashed after install when running "adonis serve --dev"

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [adonisjs/adonis-framework#1077]
```
λ adonis serve --dev

 SERVER STARTED
> Watching files for changes...

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@adonisjs/ignitor'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\dev\Work\RyS\TODOer\server\server.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Application crashed, make sure to kill all related running process, fix the issue and re-run the app
```

I'm using Node v10.15.3 on Windows 10

**Comment by Karlheinzniebuhr** [comment]
Solved by deleting node_modules and running
`npm install`
