### ISSUE TITLE
npm start command fails on ubuntu/linux

### ISSUE THREAD

**Issue by darmie** [adonisjs/adonis-framework#125]
Hi, I tried running my adonis app on a live Ubuntu 14.10 server and `npm start` fails. NodeJS version is `0.10.25` and npm version is `1.4.21`

Error message:

```log
> adonis-app@2.0.0 start /var/www/kangpe_web
> node --harmony_proxies server.js

Error: unrecognized flag --harmony_proxies
Try --help for options

/var/www/kangpe_web/bootstrap/http.js:72
      use(`${appNameSpace}/Http/kernel`)
          ^

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:406:25)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at require (module.js:355:19)
    at Object.<anonymous> (/var/www/kangpe_web/server.js:13:1)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)

npm ERR! adonis-app@2.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-app@2.0.0 start script.
npm ERR! This is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_proxies server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /var/www/kangpe_web
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/kangpe_web/npm-debug.log
npm ERR! not ok code 0
```

**Comment by thetutlage** [comment]
According to documentation http://adonisjs.com/docs/2.0/installation , Adonis needs node 4.0 or great

**Comment by darmie** [comment]
Ok thanks. I'll try to use NVM to install the latest
