### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by tinkone** [adonisjs/adonis-framework#150]
Came upon this error while starting up, still runs. Not sure why the message starting coming up

```
/home/user/prjx/bootstrap/http.js:13
const fold = require('adonis-fold')
^^^^^
[BS] Proxying: http://localhost:3333
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:4001
    External: http://192.168.11.150:4001
 ---------------------------------------
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)



````

partial package.json
```
   "adonis-ace": "^2.0.7",
    "adonis-commands": "^2.0.3",
    "adonis-fold": "^2.0.1",
    "adonis-framework": "^2.0.9",
    "adonis-lucid": "^2.0.5",
    "adonis-middleware": "^1.0.5",
```

**Comment by tinkone** [comment]
Nevermind had a dumb out. I was on the wrong node version.
