### ISSUE TITLE
Allow for mp4 and webm to be served out of the box

### ISSUE THREAD

**Issue by michaeljcalkins** [adonisjs/adonis-framework#151]
I have a fresh install of Adonis and some of my static files are not being served.

This is a straight port from express 4 to Adonis where everything was being served correctly.

![screen shot 2016-04-28 at 8 54 55 am](https://cloud.githubusercontent.com/assets/8272012/14892272/f10ea362-0d1e-11e6-9f6e-ce6cad420b11.png)

![screen shot 2016-04-28 at 8 57 57 am](https://cloud.githubusercontent.com/assets/8272012/14892376/6a82c386-0d1f-11e6-9c9c-9808faee37c6.png)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rangersteve@2.0.0~prestart: rangersteve@2.0.0
6 silly lifecycle rangersteve@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle rangersteve@2.0.0~start: rangersteve@2.0.0
8 verbose lifecycle rangersteve@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle rangersteve@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/michaelcalkins/Code/rangersteve/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michaelcalkins/.composer/vendor/bin:/Users/michaelcalkins/.rvm/bin
10 verbose lifecycle rangersteve@2.0.0~start: CWD: /Users/michaelcalkins/Code/rangersteve
11 silly lifecycle rangersteve@2.0.0~start: Args: [ '-c', 'node --harmony_proxies server.js' ]
12 silly lifecycle rangersteve@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle rangersteve@2.0.0~start: Failed to exec start script
14 verbose stack Error: rangersteve@2.0.0 start: `node --harmony_proxies server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid rangersteve@2.0.0
16 verbose cwd /Users/michaelcalkins/Code/rangersteve
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error rangersteve@2.0.0 start: `node --harmony_proxies server.js`
22 error Exit status 1
23 error Failed at the rangersteve@2.0.0 start script 'node --harmony_proxies server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rangersteve package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node --harmony_proxies server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rangersteve
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rangersteve
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
 ```

**Comment by thetutlage** [comment]
Is it version `2.0` or the `dev` release. May be if you can share the command u used to create the project

**Comment by michaeljcalkins** [comment]
Version 2.0

1. adonis new yardstick
2. I moved my existing project `rangersteve` into BACKUP_FILES
3. I copied `yardstick` and pasted it into `rangersteve`
4. I began converting my `rangersteve` express code into the files from the generated `yardstick` code

**Comment by thetutlage** [comment]
Okay, make sense.

So the `dev` release is going to be 3.0 soon and it has handful of improvements + new features. Also in 3.0 i have moved to `node-static` to `serve-static`. 

Can u create the new project using

```bash
adonis new yardstick --dev
```

Moving from 2.0 to dev will be transparent for you, since you have just started migrating your project.

**Comment by michaeljcalkins** [comment]
Got it I'll give that a shot today!

**Comment by michaeljcalkins** [comment]
It worked! :)
