### ISSUE TITLE
Error when initializing project

### ISSUE THREAD

**Issue by krisanalfa** [adonisjs/adonis-framework#164]
When I run `adonis new adonan`, I got this error:

```
Cloning into 'adonan'...
cleaning project
setting up app key
Fixing ace file
installing dependencies may take a while
installing dependencies... \npm ERR! Linux 4.5.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at markDeps (/usr/lib/node_modules/npm/lib/install/deps.js:106:5)
npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/usr/lib/node_modules/npm/lib/install/deps.js:147:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
installing dependencies... /
npm ERR! Please include the following file with any support request:
npm ERR!     /home/alfa/workspaces/mine/adonan/npm-debug.log
undefined
```

My system:
- OS: Arch Linux
- Kernel: `Linux sven 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux`
- nodejs: v6.1.0
- npm: v3.9.0

**Comment by thetutlage** [comment]
Related to #161. Let's chat there
