### ISSUE TITLE
Can't serve a fresh install

### ISSUE THREAD

**Issue by vieks** [adonisjs/adonis-framework#2]
I have lastest node version installed
`nove -v >>> v4.1.0` 

Then I follow those steps:
`npm install -g adonis-cli`
`adonis new test && cd test`
It's ok.

But when I try to launch app with:
`node ace server:start`

`Error: Cannot find module 'adonis-config-provider/providers/ConfigProvider'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /var/www/illyon/node_modules/adonis-fold/src/Registerar/helpers.js:31:12
    at arrayMap (/var/www/illyon/node_modules/adonis-fold/node_modules/lodash/index.js:1406:25)
    at Function.map (/var/www/illyon/node_modules/adonis-fold/node_modules/lodash/index.js:6710:14)
    at Object.RegisterarHelpers.requireHash (/var/www/illyon/node_modules/adonis-fold/src/Registerar/helpers.js:30:22)
    at /var/www/illyon/node_modules/adonis-fold/src/Registerar/index.js:29:35
    at Object.Registerar.register (/var/www/illyon/node_modules/adonis-fold/src/Registerar/index.js:27:10)`

It seems the 'index.js' file is forgotten into 'adonis-config-provider/providers/ConfigProvider' path.

**Comment by thetutlage** [comment]
Strange, can you delete everything from `node_modules` and do `npm install` again?

**Comment by vieks** [comment]
Of course !

![step-1](http://puu.sh/kjelV/c108f81fc0.png)

![step-2](http://puu.sh/kjepF/0d68dc8f9b.png)


Still the same error :(

**Comment by thetutlage** [comment]
Yes there is a typo error , config provider is named `configProvider` and i am using it as `ConfigProvider`. Mac is not case sensitive so i missed it.

Updating config provider in a min but will quickly boot a virtual ubuntu machine to test typo errors.

**Comment by vieks** [comment]
No problems take your time ;)
Thanks.
