### ISSUE TITLE
after creating  adonis app (master 3.0.0), adonis fails to run

### ISSUE THREAD

**Issue by rkrishnamoorthy** [adonisjs/adonis-framework#201]
Steps to replicate
```

Macintoshs-MacBook-Pro% adonis new nb
Cloning into 'nb'...
cleaning project
setting up app key
Fixing ace file
installing dependencies may take a while
installing dependencies... \
> fsevents@1.0.12 install /Users/rk/projects/nbfuel/nb/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

installing dependencies... /[fsevents] Success: "/Users/rk/projects/nbfuel/nb/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
installing dependencies... -nodemon@1.9.2 node_modules/nodemon
... 
--------------------------------------
   GETTING STARTED
--------------------------------------
1. cd nb
2. npm start


Macintoshs-MacBook-Pro% cd nb
Macintoshs-MacBook-Pro% npm start

> adonis-app@3.0.0 start /Users/rk/projects/nbfuel/nb
> node --harmony_proxies server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'adonis-fold'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rk/projects/nbfuel/nb/bootstrap/http.js:14:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-app@3.0.0 start script 'node --harmony_proxies server.js'.
npm ERR! This is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_proxies server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rk/projects/nbfuel/nb/npm-debug.log
Macintoshs-MacBook-Pro%


```
Package.json:
```
{
  "name": "adonis-app",
  "version": "3.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x 'node --harmony_proxies' server.js",
    "start": "node --harmony_proxies server.js"
  },
  "author": "",
  "license": "MIT",
  "description": "",
  "private": true,
  "dependencies": {
    "adonis-ace": "^3.0.1",
    "adonis-auth": "^1.0.0",
    "adonis-commands": "^2.1.0",
    "adonis-fold": "^3.0.2",
    "adonis-framework": "^3.0.0",
    "adonis-lucid": "^3.0.1",
    "adonis-middleware": "^1.0.6",
    "youch": "^1.0.1"
  },
  "autoload": {
    "App": "./app"
  },
  "devDependencies": {
    "nodemon": "^1.9.1"
  }
}
```
After that, i installed adonis-fold using a npm install 

`Macintoshs-MacBook-Pro% npm install --save adonis-fold
adonis-fold@3.0.2 node_modules/adonis-fold
├── co@4.6.0
├── dwell@1.0.0
├── lodash@3.10.1
├── require-stack@1.0.2 (syntax-error@1.1.6)
├── co-parallel@1.0.0 (co-thread@0.0.1)
└── cat-log@1.0.2 (ms@0.7.1, npmlog@2.0.4)`

```
```

Errror: Cannot find module 'adonis-framework/providers/ConfigProvider'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireStack (/Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/node_modules/require-stack/src/index.js:44:12)
    at /Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/src/Registrar/index.js:29:20
    at arrayMap (/Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/node_modules/lodash/index.js:1406:25)
    at map (/Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/node_modules/lodash/index.js:6710:14)
    at interceptor (/Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/node_modules/lodash/index.js:12240:26)
    at thru (/Users/rk/projects/nbfuel/nb/node_modules/adonis-fold/node_modules/lodash/index.js:5927:26)

```

**Comment by lordpixel** [comment]
What is the content of your file:

/Users/rk/projects/nbfuel/nb/npm-debug.log

**Comment by lordpixel** [comment]
Also, please try running the app using the following command:

`npm run dev`

It should start the app in development mode, where your changes are monitored by nodemon to perform hot-reloads.

**Comment by RomainLanz** [comment]
Which version of `node` and `npm` are you using?

**Comment by rkrishnamoorthy** [comment]
All, thanks for the quick reply. 
This was my bad as I had downgraded NPM due to the symlinking issue and I forgot about it

Closing this issue

**Comment by Metehan** [comment]
@rkrishnamoorthy thank you your tip solved my problem :+1:
