### ISSUE TITLE
CSRF setting in shield.js has no effect

### ISSUE THREAD

**Issue by rkrishnamoorthy** [adonisjs/adonis-framework#221]
when I have this as CSRF setting,
```
 csrf: {
    enable: false,
    methods: ['POST', 'PUT', 'DELETE'],
    filterUris: []
  }
```

i still see these errors

> Error: csrf secret missing
>     at Shield._validateCsrf (/Users/rk/projects/42select/node_modules/adonis-middleware/src/Shield/index.js:161:21)
>     at Shield.handle (/Users/rk/projects/42select/node_modules/adonis-middleware/src/Shield/index.js:231:12)
>     at next (native)
>     at onFulfilled (/Users/rk/projects/42select/node_modules/co/index.js:65:19)
>     at process._tickCallback (node.js:369:9)

Am i doing something wrong ?

**Comment by rkrishnamoorthy** [comment]
Not an issue. this is my bad after some more investigation
