### ISSUE TITLE
Form Builder: Improve error messages when controller binding has any errors

### ISSUE THREAD

**Issue by connor11528** [adonisjs/adonis-framework#222]
I would like to create a form to add companies using Form Builder. I have this in my template:

```
{% extends 'master' %}

{% block content %}
	<div class='row'>
	<h1>Companies</h1>

	<h3>Add company</h3>
		{{ form.open({action: 'CompanyController.update' }) }}
			{{ form.label('name', 'Enter Company Name') }}
			{{ form.text('name'), '', {class: 'input'} }}
		{{ form.close() }}
	</div>
{% endblock %}
```

But I get a template render error:

```
Template render error: (/Users/connorleech/Projects/adonis-tutorial/resources/views/companies.njk) [Line 9, Column 22]
  expected variable end
    at Object.exports.prettifyError (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:468:27)
    at /Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:311:35
    at createTemplate (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:249:25)
    at /Users/connorleech/Projects/adonis-tutorial/node_modules/adonis-framework/src/View/loader.js:54:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

What is the `end` variable and where must it go? Thank you!

**Comment by connor11528** [comment]
Okay, changed up my form structure to follow [tutorial](http://www.adonisjs.com/docs/3.0/adonis-blog-part5#form-builder) and now get a new error:

```
Template render error: (/Users/connorleech/Projects/adonis-tutorial/resources/views/companies.njk) [Line 7, Column 12]
  TypeError: Cannot read property 'verb' of undefined
    at Object.exports.prettifyError (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:485:31
    at eval (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:10:11)
    at b_content (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:54:3)
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:9:86)
    at eval (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:20:16)
    at eval (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:15:46)
    at eval (eval at <anonymous> (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:15:86)
    at createTemplate (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/connorleech/Projects/adonis-tutorial/node_modules/nunjucks/src/environment.js:249:25)
```

Where the updated view looks like:

```
{% extends 'master' %}

{% block content %}
	<div class='row'>
	<h1>Companies</h1>

	<h3>Add company</h3>
		{{ form.open({action: 'CompanyController.update' }) }}

			{{ csrfField }}
			
			<fieldset class="form-group">
      			{{ form.label('Company Name') }}
      			{{ form.text('name', null, { class: 'form-control' }) }}
    		</fieldset>

			<fieldset class="form-group">
      			{{ form.label('Address') }}
      			{{ form.textarea('address', null, { class: 'form-control' }) }}
    		</fieldset>

    		{{ form.submit('Add', 'create', { class: 'btn btn-primary btn-block' }) }}

		{{ form.close() }}
	</div>
{% endblock %}
```

Why are these errors happening? Is there any more documentation on these error messages for using Form Builder?

**Comment by connor11528** [comment]
Okay so an issue that fixed these view rendering errors was that my controller method did not exist. 

Changed it to `{{ form.open({action: 'CompanyController.create' }) }}` and my controller looks like this:

```
'use strict'

class CompanyController {
	* create (request, response) {
      yield response.sendView('companies')
  }
}

module.exports = CompanyController
```

**Comment by thetutlage** [comment]
@connor11528 I will improve the error message to make sure it has more context to debug properly. Opening the issue, so that I should remember that I have to work on this

**Comment by connor11528** [comment]
Okay got it!

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonis-framework/commit/fd0c0085e9962f345e6e793edf664eb40945b9e2

**Comment by connor11528** [comment]
Thank you! Much appreciated #adonisftw
