### ISSUE TITLE
'set' on proxy: trap returned falsish for property '_notFlag'

### ISSUE THREAD

**Issue by demirhancosku** [adonisjs/adonis-framework#296]
Hi there,
I just migrate my adonis application centos / node v5.x to ubuntu / node v6.x, but I cant figure out why I'm getting this error;
`
'set' on proxy: trap returned falsish for property '_notFlag'
`

btw my mysql service is up.

`
TypeError: 'set' on proxy: trap returned falsish for property '_notFlag'
    at Proxy._not (/var/www/html/analytics/node_modules/knex/lib/query/builder.js:726:19)
    at Proxy.whereNull (/var/www/html/analytics/node_modules/knex/lib/query/builder.js:340:17)
    at Proxy.where (/var/www/html/analytics/node_modules/knex/lib/query/builder.js:176:21)
    at AuthApp.handle (/var/www/html/analytics/app/Http/Middleware/AuthApp.js:23:38)
    at next (native)
    at /var/www/html/analytics/node_modules/adonis-framework/src/Middleware/index.js:162:13
    at next (native)
    at onFulfilled (/var/www/html/analytics/node_modules/co/index.js:65:19)
    at /var/www/html/analytics/node_modules/co/index.js:54:5
    at co (/var/www/html/analytics/node_modules/co/index.js:50:10)
    at toPromise (/var/www/html/analytics/node_modules/co/index.js:118:63)
    at next (/var/www/html/analytics/node_modules/co/index.js:99:29)
    at onFulfilled (/var/www/html/analytics/node_modules/co/index.js:69:7)
    at /var/www/html/analytics/node_modules/co/index.js:54:5
    at co (/var/www/html/analytics/node_modules/co/index.js:50:10)
    at Object.helpers.callRouteAction (/var/www/html/analytics/node_modules/adonis-framework/src/Server/helpers.js:29:3)
    at Server._finalHandler (/var/www/html/analytics/node_modules/adonis-framework/src/Server/index.js:43:15)
    at finalHandler (/var/www/html/analytics/node_modules/adonis-framework/src/Server/index.js:91:12)
    at next (native)
    at onFulfilled (/var/www/html/analytics/node_modules/co/index.js:65:19)
    at /var/www/html/analytics/node_modules/co/index.js:54:5
    at co (/var/www/html/analytics/node_modules/co/index.js:50:10)
`

Middleware (first query)
`
        const appdetails =  AppModel.where('appKey', appKey).first();
`

**Comment by thetutlage** [comment]
What version of `adonis-lucid` are you using?

**Comment by thetutlage** [comment]
Closing since no follow up by the issue reporter
