### ISSUE TITLE
Middleware issue

### ISSUE THREAD

**Issue by wtser** [adonisjs/adonis-framework#30]
code in kernel.js

```
const namedMiddlewares = {
  'auth':'App/Http/Middleware/Authentication'

}
```

router

```
Route
  .get('/admin/dashboard','AdminController.dashboard')
  .middleware(['auth'])
```

error

```
ReferenceError: namedMiddlewares is not defined
    at Object.<anonymous> (/Users/wangtieshou/Project/tenread-weekly/app/Http/kernel.js:42:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.Loader.require (/Users/wangtieshou/Project/tenread-weekly/node_modules/adonis-fold/src/Loader/index.js:32:12)
    at Object.Loader._makeDump (/Users/wangtieshou/Project/tenread-weekly/node_modules/adonis-fold/src/Loader/index.js:155:17)
    at Object.Loader.resolveUsingType (/Users/wangtieshou/Project/tenread-weekly/node_modules/adonis-fold/src/Loader/index.js:93:27)
    at Ioc.use (/Users/wangtieshou/Project/tenread-weekly/node_modules/adonis-fold/src/Ioc/index.js:227:30)
    at /Users/wangtieshou/Project/tenread-weekly/bootstrap/http.js:69:5
    at process._tickCallback (node.js:377:9)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by thetutlage** [comment]
Can you paste your entire `kernel.js` file

**Comment by wtser** [comment]
```
'use strict'
/*
|--------------------------------------------------------------------------
|   Middlewares
|--------------------------------------------------------------------------
|
|  Here you define http request specific middlewares, global middlewares
|  will be invoked on every request , where as named middlewares can
|  be bind to a route or group using it's name.
|
*/

const Middleware = use('Middleware')

/*
|--------------------------------------------------------------------------
|   Global Middlewares
|--------------------------------------------------------------------------
|
|   Global middlewares will be executed on every http request.
|
*/
const globalMiddlewares = [
  'App/Http/Middleware/BodyParser'
]

/*
|--------------------------------------------------------------------------
|   Named Middlewares
|--------------------------------------------------------------------------
|
|   Named middlewares are key/value pairs that can be referenced on
|   routes using unique keys
|
*/
const namedMiddlewares = {
  'auth':'App/Http/Middleware/Authentication'

}

Middleware.global(globalMiddlewares)
Middleware.named(namedMiddlewares)

```

**Comment by thetutlage** [comment]
hahahaha, this is weird. `namedMiddlewares` is clearly defined. Any chance of pushing your code to github, so that i can have a look

**Comment by wtser** [comment]
ok , u can view it at https://github.com/wtser/ten-read-weekly

**Comment by RomainLanz** [comment]
Where's your Middleware?

https://github.com/wtser/ten-read-weekly/tree/master/app/Http/Middleware

**Comment by thetutlage** [comment]
I am not sure how you are getting these errors , ideally `Route.middleware` is not a function it has to be `middlewares`. Check below

```javascript
Route
  .get('/admin/dashboard','AdminController.dashboard')
  .middlewares(['auth'])
```

**Comment by wtser** [comment]
@RomainLanz added it

**Comment by RomainLanz** [comment]
```
/**
 * @function middlewares
 * @description assign array of named middlewares to route
 * @param  {Array} arrayOfNamedMiddleware
 * @public
 */
Route.middlewares = function (arrayOfNamedMiddleware) {
  // ...

  return this
}
```

**Comment by wtser** [comment]
misunderstand by the document
![](http://sfault-image.b0.upaiyun.com/291/966/2919661011-5669279e90da4_articlex)

using Route.middlewares is right

**Comment by thetutlage** [comment]
My Bad, will correct it
