### ISSUE TITLE
Install fails on Windows 10

### ISSUE THREAD

**Issue by LeonardHarley** [adonisjs/adonis-framework#302]
Adonis on windows fails to start...

```> adonis-app@3.0.0 start C:\Code\adonis
> node --harmony_proxies server.js

info adonis:framework +10ms serving app on 10.10.10.151:8081
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 10.10.10.151:8081
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\Len\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! adonis-app@3.0.0 start: `node --harmony_proxies server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adonis-app@3.0.0 start script 'node --harmony_proxies server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adonis-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_proxies server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adonis-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adonis-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\adonis\npm-debug.log```

**Comment by thetutlage** [comment]
`EADDRNOTAVAIL 10.10.10.151:8081` port or host is not available

**Comment by LeonardHarley** [comment]
Hi - that IP is simply related to my local setup.

Although the problem is not resolved I'm actually going to close the issue.

In the end I installed Adonis inside a Vagrant VM and used [sympm](https://github.com/ezekg/sympm) to overcome the known node_modules install issue with mapping Vagrant folders to a Win host OS ...

**Comment by svscorp** [comment]
Sad that it's not resolved :(

**Comment by RomainLanz** [comment]
Hey @svscorp !

The problem was that the IP:PORT used was already used by another application.
This is not an Adonis issue since you can change those inside your `.env` file.

If you encounter any others issues please create a new one.

**Comment by svscorp** [comment]
@RomainLanz 

I am getting exactly the same thing on Windows10. And my **netstat -a -b** doesn't show anything using 3333.

````
info adonis:framework [Thu May 11 2017 14:08:59 GMT+0200 (W. Europe Daylight Time)] serving app on localhost:3333
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3333
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
[nodemon] app crashed - waiting for file changes before starting...
````

**Comment by svscorp** [comment]
@RomainLanz 

Though, changing the port to anything else - just works... Strange...
