### ISSUE TITLE
TypeError: Generator is already running

### ISSUE THREAD

**Issue by blogui91** [adonisjs/adonis-framework#339]
Hello!
Congratulations to the person (or people) who has dedicated time to make this awesome framework, i am coming from Laravel and i have to say i was looking for exactly this kind of framework since some months ago . i'm really really surpriced! 💯 

Unfortunately i am struggling with something, i would like to run the project in a server (in develop) and visualize it from other computer.

my .env looks like 

```
HOST=0.0.0.0 // I tried with localhost and 127.0.0.1
PORT=8000
APP_KEY=SfWwYfeKKNQkqHyXU7sib8ADqUsT8xh4
NODE_ENV=development
CACHE_VIEWS=false
SESSION_DRIVER=cookie
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_USER=root
DB_PASSWORD=
DB_DATABASE=adonis
```

i write http://192.168.1.68:8000  to run my project and i get this error in terminal and browser

```
info adonis:framework +10ms serving app on 0.0.0.0:8000
TypeError: Generator is already running
    at throw (native)
    at onRejected (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:81:24)
    at next (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:101:14)
    at onFulfilled (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:69:7)
    at /Users/blogui91/Documents/adonis-app/node_modules/co/index.js:54:5
    at co (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:50:10)
    at toPromise (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:118:63)
    at next (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/blogui91/Documents/adonis-app/node_modules/co/index.js:69:7)
    at /Users/blogui91/Documents/adonis-app/node_modules/co/index.js:54:5
```

I supposed the conflict was in the script `npm run dev`  so i just ran `nodemon server.js` and it worked. However, the project may not work correctly. is it a bug??

**Comment by thetutlage** [comment]
Can u share the script next to `dev` inside the `package.json` file with the Node.Js version

**Comment by blogui91** [comment]
Oh sorry, i forgot to mention some things that i changed,  I as have Node  v6.5.0, 
I had conflict with harmony, reading a thread someone said changing version of node to 4.5 it would be fixed so i changed the original script to this

```"dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x \"node --harmony\" server.js"```

**Comment by thetutlage** [comment]
Adonis does not rely on any other thing apart from `harmony proxies` which is included by default in node.js 6.0 or greater.

In short you do not need the `--harmony` flag

**Comment by thetutlage** [comment]
Closing since no activity from reporter
