### ISSUE TITLE
Get user frow JWT

### ISSUE THREAD

**Issue by theobouwman** [adonisjs/adonis-framework#383]
Is it possible to fetch the user from a given JWT?
If you store the JWT in a app after authenticating, then reauthenticate the user with the saved JWT.

Is that possible?

**Comment by thetutlage** [comment]
You mean fetch the user on the server?

**Comment by theobouwman** [comment]
@thetutlage yes, fetch the user form the JWT. The JWT is linked to the user right?

**Comment by thetutlage** [comment]
If your primary authenticator is JWT, then you can do

```javascript
yield request.auth.getUser()
```

If not

```javascript
yield request.auth.authenticator('jwt').getUser()
```

**Comment by theobouwman** [comment]
@thetutlage I mean to Authenticate the user from the JWT.

**Comment by thetutlage** [comment]
You should have access to the user before generate the JWT token. If you would like to authenticate them using their `email` and `password` consider using `attempt` method. http://adonisjs.com/docs/3.1/authentication#_attempt_uid_password_2

**Comment by thetutlage** [comment]
Closing since no activity from the reporter and does not seems to be a bug

**Comment by utsavstha** [comment]
I could not get user from token using this method:
`      let users = await request.auth.getUser()`

Error log: 
TypeError: Cannot read property 'getUser' of undefined
    at ProductController.index (/Users/utsavstha/Projects/InventorySystem/app/Controllers/Http/ProductController.js:34:38)
    at <anonymous>

**Comment by utsavstha** [comment]
> I could not get user from token using this method:
> ` let users = await request.auth.getUser()`
> 
> Error log:
> TypeError: Cannot read property 'getUser' of undefined
> at ProductController.index (/Users/utsavstha/Projects/InventorySystem/app/Controllers/Http/ProductController.js:34:38)
> at

Looks like the method has changed:

I used:
`      let users = await auth.getUser()`
instead of:
`      let users = await request.auth.getUser()`

and its working now.

I also had to add auth to method parameter like:
`  async index ({ request, auth, response }) {}
`

**Comment by RomainLanz** [comment]
@utsavstha You are commenting on a old issue that use Adonis 3.2. This is why things have changed.

**Comment by ing-mario** [comment]
async GetUser({auth, response}){

    try {
      let user = await auth.getUser()
      return response.send(user);
    } catch (e) {
      response.send('Token invalid')
    }
  }
