### ISSUE TITLE
Middleware: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by milosdakic** [adonisjs/adonis-framework#413]
Keep seeing this error in the terminal. Seems to trip up the middleware layer.

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at /node_modules/adonis-framework/src/Middleware/index.js:248:20
    at next (native)
    at onFulfilled (/node_modules/co/index.js:65:19)
    at /node_modules/co/index.js:54:5
    at co (/node_modules/co/index.js:50:10)
    at toPromise (/node_modules/co/index.js:118:63)
    at next (/node_modules/co/index.js:99:29)
    at onFulfilled (/node_modules/co/index.js:69:7)
    at /node_modules/co/index.js:54:5
    at co (/node_modules/co/index.js:50:10)
```

**Comment by thetutlage** [comment]
Are you running any custom middleware?

**Comment by milosdakic** [comment]
@thetutlage No, wasn't running any. Found the problem.

In your controller make sure you have `*` before the method name.
```
* index (request, response) { }
```

**Comment by liseipi** [comment]
I want to use this.ctx in a helper file, if?

**Comment by liseipi** [comment]
```
class AlertPrompt {

  static async handle (args) {

    console.log(args)
    const {title, type, message, responseURL} = args

    this.ctx.session.flash({
      notification: {
        title: title,
        type: type,
        message: message
      }
    })
    await this.ctx.session.commit()

    return this.ctx.response.redirect(responseURL || 'back')

  }

}

module.exports = AlertPrompt
```
