### ISSUE TITLE
Useless strack traces

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-framework#455]
When an error is thrown, the stacktrace consists of a relevant error message, but the trace it's self seems to only point at the error handler code

```
ReferenceError: user is not defined
    at Server._handleError (/Users/mike/dev/ad/node_modules/adonis-framework/src/Server/index.js:108:11)
    at co.catch (/Users/mike/dev/ad/node_modules/adonis-framework/src/Server/index.js:150:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This makes debugging very difficult. I don't know if this is a node or Adonis issue,  (Sorry, I am new to nodeJS frameworks and have chosen Adonis based on years of Laravel use).

**Comment by thetutlage** [comment]
What does the code look like? Where exactly the `user` is undefined?

**Comment by mikehhhhhhh** [comment]
It was a mis-typed "use" statement. 

But my question is more about the stack traces in general. Why are they not showing the same depth/level of stack trace as a typical node app? Can/will this be fixed?

**Comment by SAGV** [comment]
I've hit these stacktraces a few times in the last few days. I'll post here an example whenever I hit it again…

**Comment by SAGV** [comment]
For example, I have a middleware with this code:
```
const Errors  = use('Errors')

class RestrictUnauthorized {

  * handle (request, response, next) {
    console.log(req.user)
    yield next
  }

}

module.exports = RestrictUnauthorized
```

Where `req` is not defined. So the error output would be:
```
ReferenceError: req is not defined
    at Server._handleError (/Users/tema/Sites/ovelo-adonis/node_modules/adonis-framework/src/Server/index.js:108:11)
    at co.catch (/Users/tema/Sites/ovelo-adonis/node_modules/adonis-framework/src/Server/index.js:150:12)
```

**Comment by thetutlage** [comment]
@SAGV Mind sharing the `adonis-framework` version from the package.json file.

**Comment by SAGV** [comment]
@thetutlage it is 3.0.8

**Comment by thetutlage** [comment]
Mind updating to `3.0.9` and then re-try the same thing?

**Comment by thetutlage** [comment]
This commit https://github.com/adonisjs/adonis-framework/commit/90081facc85e654dbdc72c6042cbee832daeae67 fixed one of the known error stack issue.

Also error stack gets weird in Node.js, since at certain situations v8 does not return helpful stack traces and I believe everyone including and v8 are trying to come up with better outputs in the future

**Comment by SAGV** [comment]
Yes, it is fixed now!

**Comment by thetutlage** [comment]
👍

**Comment by mikehhhhhhh** [comment]
@thetutlage I can confirm that 3.0.9 gives me the kind of stack trace I'd expect. 

Thank you!

**Comment by thetutlage** [comment]
That is great! Happy endings. Closing the issue

**Comment by SAGV** [comment]
Thank you ;-)

**Comment by mikehhhhhhh** [comment]
Am I able to re-open this @thetutlage ? It seems pointless to create a new issue. 

When a 404 happens, the following trace it outputted to STDOUT
```Error
    at Server._callRouteAction (/Users/mike/dev/appii-js/node_modules/adonis-framework/src/Server/index.js:73:13)
    at finalHandler (/Users/mike/dev/appii-js/node_modules/adonis-framework/src/Server/index.js:212:18)
    at finalHandler.next (<anonymous>)
    at onFulfilled (/Users/mike/dev/appii-js/node_modules/co/index.js:65:19)
    at /Users/mike/dev/appii-js/node_modules/co/index.js:54:5
    at co (/Users/mike/dev/appii-js/node_modules/co/index.js:50:10)
    at toPromise (/Users/mike/dev/appii-js/node_modules/co/index.js:118:63)
    at next (/Users/mike/dev/appii-js/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/mike/dev/appii-js/node_modules/co/index.js:69:7)
(/Users/mike/dev/appii-js/node_modules/adonis-framework/src/Server/index.jsError
    at Server._callRouteAction (/Users/mike/dev/appii-js/node_modules/adonis-framework/src/Server/index.js:73:13)```

An exception is thrown with a suitable error message in Server/index.js:73, should this error message be output on the console? 

This could also end up needlessly filling up logs in production, perhaps one single line for a 404 would be sufficient?

**Comment by RomainLanz** [comment]
You should edit the error handler method and instead of displaying the stack you should only display the message.

```
// app/Listeners/Http.js
console.error(error.message) // instead of error.stack
```

**Comment by mikehhhhhhh** [comment]
Oh, so it's up to me to configure this per application. That's great, thanks.
