### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by discoverlance-com** [adonisjs/adonis-framework#4635]
### Package version

6.9.1

### Describe the bug

I am running the build command and getting the following error

My NODE VERSION: v20.15.0

```
error during build:
../../node_modules/@poppinss/utils/build/chunk-K76IL3UP.js (52:9): "randomBytes" is not exported by "__vite-browser-external:crypto", imported by "../../node_modules/@poppinss/utils/build/chunk-K76IL3UP.js".
file: /workspace/host/node_modules/@poppinss/utils/build/chunk-K76IL3UP.js:52:9

50: 
51: // src/string/random.ts
52: import { randomBytes } from "crypto";
             ^
53: function random(size) {
54:   const bits = (size + 1) * 6;

    at getRollupError (file:///workspace/host/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///workspace/host/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at Module.error (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:13858:16)
    at Module.traceVariable (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:14306:29)
    at ModuleScope.findVariable (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
    at FunctionScope.findVariable (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at FunctionBodyScope.findVariable (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at Identifier.bind (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:6908:40)
    at CallExpression.bind (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
    at CallExpression.bind (file:///workspace/host/node_modules/rollup/dist/es/shared/node-entry.js:9135:15)

```

### Reproduction repo

https://github.com/discoverlance-com/adonis-build-error

**Comment by RomainLanz** [comment]
Hey @discoverlance-com! 👋🏻 

We need more information to help you.
The best would be to have a repository with **the minimum amount of code** to reproduce your issue.

**Comment by discoverlance-com** [comment]
> Hey @discoverlance-com! 👋🏻 
> 
> We need more information to help you.
> The best would be to have a repository with **the minimum amount of code** to reproduce your issue.

Ok sure, let me share that in a bit. I have been using gitpod so I have to create a new Adonis project from there.

**Comment by discoverlance-com** [comment]
> Hey @discoverlance-com! 👋🏻
> 
> We need more information to help you. The best would be to have a repository with **the minimum amount of code** to reproduce your issue.

Hi, I added the minimum reproducible to the main issue description. Also added here (https://github.com/discoverlance-com/adonis-build-error) just in case. Thanks

**Comment by Julien-R44** [comment]
Read the error carefully. You're importing backend code into your frontend

Here https://github.com/discoverlance-com/adonis-build-error/blob/main/inertia/components/shared/breadcrumbs.tsx#L6

**Comment by discoverlance-com** [comment]
> Read the error carefully. You're importing backend code into your frontend
> 
> Here https://github.com/discoverlance-com/adonis-build-error/blob/main/inertia/components/shared/breadcrumbs.tsx#L6

Oh yes, I see that now. I assumed the utility function will work anywhere in the adonis project. I didn't know it only works on the backend.  So it looks like I have to find alternatives for the frontend. Thanks for this.
