### ISSUE TITLE
How to do a whereRaw() using LIKE clause

### ISSUE THREAD

**Issue by lmj0011** [adonisjs/adonis-framework#475]
I have the following

```js
* index (request, response) {
    const pageNum = request.input('page', 1)
    const perPage = request.input('per_page', 10)
    const filter = request.input('filter', null)
    let data = {}

    if (filter) {
      data = yield Instance
      .query().whereRaw(`'name' LIKE '%${filter}%'`)
      .paginate(pageNum, perPage)
    } else {
      data = yield Instance.paginate(pageNum, perPage)
    }

    response.ok(data)
  }
```

passing a string for the `filter` throws this error

```
TypeError: The operator "undefined" is not permitted
    at Formatter.operator (/home/landan/www/adonuxt-rp/node_modules/knex/lib/formatter.js:138:13)
    at QueryCompiler_MySQL.whereBasic (/home/landan/www/adonuxt-rp/node_modules/knex/lib/query/compiler.js:525:100)
    at QueryCompiler_MySQL.where (/home/landan/www/adonuxt-rp/node_modules/knex/lib/query/compiler.js:314:32)
    at /home/landan/www/adonuxt-rp/node_modules/knex/lib/query/compiler.js:147:30
    at Array.map (native)
    at QueryCompiler_MySQL.select (/home/landan/www/adonuxt-rp/node_modules/knex/lib/query/compiler.js:146:33)
    at QueryCompiler_MySQL.toSQL (/home/landan/www/adonuxt-rp/node_modules/knex/lib/query/compiler.js:108:27)
    at Builder.toSQL (/home/landan/www/adonuxt-rp/node_modules/knex/lib/query/builder.js:111:44)
    at /home/landan/www/adonuxt-rp/node_modules/knex/lib/runner.js:52:32
    at tryCatcher (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/util.js:16:23)
    at /home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/landan/www/adonuxt-rp/node_modules/bluebird/js/release/promise.js:636:18)
ous
```

**Comment by lmj0011** [comment]
mistake on my part

instead of:

```js
if (filter) {
      data = yield Instance
      .query().whereRaw(`'name' LIKE '%${filter}%'`)
      .paginate(pageNum, perPage)
    } else {
      data = yield Instance.paginate(pageNum, perPage)
    }
```

I had this, which caused the error

```js
if (filter) {
      data = yield Instance
      .query().whereRaw(`'name' LIKE '%${filter}%'`)
      .paginate(pageNum, perPage)
    } else {
      data = yield Instance.paginate(pageNum, perPage)
    }
    yield Instance.paginate(pageNum, perPage)  // <---------------
```
