### ISSUE TITLE
File upload abort crashes server

### ISSUE THREAD

**Issue by exhovo** [adonisjs/adonis-framework#520]
Hi
We are using [fineuploader](https://fineuploader.com/) which has cancel button during upload. If we press on cancel we got error at node js 

> ...project-path/node_modules/adonis-middleware/src/BodyParser/index.js:111
        throw error
        ^
Error: Request aborted
    at IncomingMessage.<anonymous> (...project-path/node_modules/formidable/lib/incoming_form.js:120:19)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:284:11)
    at TLSSocket.serverSocketCloseListener (_http_server.js:297:5)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:501:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:292:16)

After investigations we founded out that it is thrown from this code block 

    form.on('error', function (error) {
        throw error
     })

**Can we somehow handle this error or is there another solution to not crash server on upload abort.**
It even crashes when during upload we refresh the page.

Thanks, Hovo.

**Comment by thetutlage** [comment]
You can catch exceptions inside the global `Http error handler`. http://adonisjs.com/docs/3.2/error-and-exceptions#_catching_exception

**Comment by exhovo** [comment]
I have tried but it's not working. And error which has been thrown is not an object it's just message.

**Comment by thetutlage** [comment]
Okay, lemme look into so that it bubbles up to the exception handler.

**Comment by exhovo** [comment]
I have tested with simple html form uploaded large file and during upload refreshed browser and got the same error.

    <form method="post" enctype="multipart/form-data" action="https://domain.com:3004/file-uploader/common/">
        <input type="file" name="upload_file">
        <button type="submit">upload</button>
    </form>

**Comment by exhovo** [comment]
Only solution which I found is duplicate adonis-middleware/src/BodyParser/index.js with changing 

    form.on('error', function (error) {
					throw error
			})

TO

    form.on('aborted', function () {
				form._error(new RequestAborted('Aborted error', 413))
				return
			})

			form.on('error', function (error) {
				if(error.name !== 'RequestAborted') {
					throw error
				}
			})

**Comment by zztv1** [comment]
Got the same issue today.

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-middleware#9

**Comment by thetutlage** [comment]
Mind testing this by installing the `adonis-middleware` repo from Github. If all is good I will release it by the end of day

**Comment by codinglabsdev** [comment]
I'm having this error when a user timeouts uploading a file. I'm using Adonis as an API only.
The endpoint is set as manually processed in ```bodyParser```

I already have ```Handler.js``` configured to handle errors.

```
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Request aborted
    at IncomingMessage.onReqAborted (/Users/milo/dev/talk-it-easy-api/node_modules/multiparty/index.js:190:17)
    at IncomingMessage.emit (events.js:223:5)
    at abortIncoming (_http_server.js:496:9)
    at socketOnClose (_http_server.js:489:3)
    at Socket.emit (events.js:228:7)
    at TCP.<anonymous> (net.js:664:12)
Emitted 'error' event on PassThrough instance at:
    at errorEventQueue (/Users/milo/dev/talk-it-easy-api/node_modules/multiparty/index.js:612:18)
    at handleError (/Users/milo/dev/talk-it-easy-api/node_modules/multiparty/index.js:204:9)
    at IncomingMessage.onReqAborted (/Users/milo/dev/talk-it-easy-api/node_modules/multiparty/index.js:190:5)
    at IncomingMessage.emit (events.js:223:5)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (net.js:664:12)
```
