### ISSUE TITLE
Cannot create property 'status' on boolean 'false'

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#558]
I do not know what to say, this error suddenly appeared.

```
Invalid parameter
TypeError: Cannot create property 'status' on boolean 'false'
    at Server._normalizeError (/home/gabriel/Sites/co-report/api/node_modules/adonis-framework/src/Server/index.js:129:18)
    at Server._handleError (/home/gabriel/Sites/co-report/api/node_modules/adonis-framework/src/Server/index.js:107:10)
    at co.catch (/home/gabriel/Sites/co-report/api/node_modules/adonis-framework/src/Server/index.js:148:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Nothing was altered in these files.

**Comment by shubhamd** [comment]
@mfgabriel92 Any pointers on how this was fixed?
