### ISSUE TITLE
Cannot find module 'config/app.js'

### ISSUE THREAD

**Issue by yeedavid** [adonisjs/adonis-framework#565]
It returns the error as below after a custom provider is registered:

Error: Cannot find module 'config/app.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

Also attached the code of my custom provider:

'use strict'

const ServiceProvider = require('adonis-fold').ServiceProvider

class VanProvider extends ServiceProvider {

  	* register() {
        this.app.bind('Adonis/Provider/MyName', function() {
            return 'Hello World'
        })
    }

    * boot () {
	    const View = use('Adonis/Src/View')
	    View.global('time', function () {
	      return new Date().getTime()
	    })
	  }
}

module.exports = VanProvider

Would you please point me out how to fix this?

**Comment by yeedavid** [comment]
Ok, I have found the fixed way: https://github.com/adonisjs/adonis-framework/issues/555
So now is going to close this ~
