### ISSUE TITLE
[minor bug] First time `adonis repl` throws ENOENT

### ISSUE THREAD

**Issue by corysimmons** [adonisjs/adonis-framework#642]
```fish
$ adonis repl                                                                                                                             2662ms  

Wed Sep 13 18:44:21 2017
> { Error: ENOENT: no such file or directory, stat '/Users/cory/.adonis_repl_history'
    at Object.fs.statSync (fs.js:954:11)
    at Repl._readHistoryFile (/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/Repl/index.js:57:10)
    at Repl.handle (/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/Repl/index.js:108:10)
    at Function.exec (/Users/cory/Desktop/Work/Worky/lister/node_modules/@adonisjs/ace/src/Command/index.js:553:28)
    at Function.commanderAction (/Users/cory/Desktop/Work/Worky/lister/node_modules/@adonisjs/ace/src/Command/index.js:534:17)
    at Command.listener (/Users/cory/Desktop/Work/Worky/lister/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/Users/cory/Desktop/Work/Worky/lister/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/cory/Desktop/Work/Worky/lister/node_modules/commander/index.js:457:21)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/cory/.adonis_repl_history' }
```

Can't read it because it doesn't exist yet. Running `adonis repl` again doesn't throw (so it created the file).

To fix, fs.stat `~/.adonis_repl_history` and `touch` it if need be.

**Comment by RomainLanz** [comment]
Hey @corysimmons 👋 

Thanks for your report!
The error will be fixed in the next release.
