### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by gcopley** [adonisjs/adonis-framework#646]
Running Adonis v4, I'm getting the error 'database is locked' anytime I try an run a migration.

It even does this if I delete the file `database/development.sqlite` and then immediately run 'adonis migration:run'. Something is locking the database preventing this. I do not have the development.sqlite file open in any editor or sqlite client.

Any ideas?

```
### Error Stack (if any)
adonis migration:run
{ Error: SQLITE_BUSY: database is locked
    at Client_SQLite3._query (/app/node_modules/knex/lib/dialects/sqlite3/index.js:138:12)
    at Client_SQLite3.query (/app/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/app/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at Runner.queryArray (/app/node_modules/knex/lib/runner.js:192:40)
    at /app/node_modules/knex/lib/runner.js:63:23
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
From previous event:
    at Runner.run (/app/node_modules/knex/lib/runner.js:51:31)
    at SchemaBuilder.Target.then (/app/node_modules/knex/lib/interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3 errno: 5, code: 'SQLITE_BUSY' }
```

**Comment by thetutlage** [comment]
Maybe something within the migrations code is causing the lock. Can u share your schema files?

**Comment by gcopley** [comment]
Sorry guys. I believe this was an issue caused by a local container solution I was using and not Adonis. I've managed to get around the problem. Thanks.

**Comment by thetutlage** [comment]
Cool, no issues. Will close the issue now
