### ISSUE TITLE
Adonis Version 3.2 does not work (cannot follow set up instructions)

### ISSUE THREAD

**Issue by computamike** [adonisjs/adonis-framework#664]
### Brief Description
Following the latest instructions from the [adonis documentation](https://adonisjs.com/docs/3.2/installation), I should be able to install version 3.2.  Following the instructions I do seem to have an adonis project created - however running the project (npm run serve:dev) presents the following error message.

### Sample Code
```

➜  Code adonis new yardstick

    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___ 
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

✔ Your current Node.js & npm version match the AdonisJs requirements!
⠇ Cloning master branch of adonisjs/adonis-app blueprint
clone: Repository cloned
clean: Repository cleaned
copy: Default environment variables copied

✔ Your application is ready!

ℹ Follow below instructions to get started
$ cd yardstick
$ npm run serve:dev

➜  Code cd yardstick   
➜  yardstick npm run serve:dev                                          

> adonis-app@3.2.1 serve:dev /Users/mikehingley/Code/yardstick
> nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/mikehingley/Code/yardstick/app/**/* /Users/mikehingley/Code/yardstick/bootstrap/**/* /Users/mikehingley/Code/yardstick/config/**/* .env
[nodemon] starting `node server.js`
module.js:529
    throw err;
    ^

Error: Cannot find module 'adonis-fold'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mikehingley/Code/yardstick/bootstrap/http.js:14:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by computamike** [comment]
Speaking with @RomainLanz on gitter - it seems that I should have run npm install.  This step is missing from the documentation, and indeed from the output from the CLI itself.

**Comment by computamike** [comment]
This might be better solved as a documentation update, or alteration to the output from the 3.2 cli.  I was pointed out the the version 4 framework (which is still in dev?) has this issue fixed?  Maybe this fix could be ported to the 3.2 version?

**Comment by thetutlage** [comment]
The 4.0 is 100% ready to be used in production and the API is stable too. So I recommend using that over 3.2 and yes will add the `npm install` step to the docs

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
