### ISSUE TITLE
Starting project, Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by hamidnabati** [adonisjs/adonis-framework#665]
## Brief

I have installed @adonisjs/auth module, to be able use JWT auth in my adonis app, but when im trying to start the project i get a exception.

### Error Stack (if any)
For help see https://nodejs.org/en/docs/inspector
TypeError: Cannot read property 'bind' of undefined
    at AuthProvider._registerAuth (E:\Projects\....\adonis-....\node_modules\@adonisjs\auth\providers\AuthProvider.js:25:13)
    at AuthProvider.register (E:\Projects\....\adonis-....\node_modules\@adonisjs\auth\providers\AuthProvider.js:98:10)
    at _.filter.map (E:\Projects\....\adonis-....\node_modules\adonis-fold\src\Registrar\index.js:47:31)
    at arrayMap (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:1406:25)
    at map (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:6710:14)
    at interceptor (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:12240:26)
    at thru (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:5927:26)
    at baseWrapperValue (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:2768:30)
    at LazyWrapper.lazyValue [as value] (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:1077:16)
    at baseWrapperValue (E:\Projects\....\adonis-....\node_modules\adonis-fold\node_modules\lodash\index.js:2761:25)
Debugger attached.
Waiting for the debugger to disconnect...

and my package.json dependencies section is:

"dependencies": {
    "@adonisjs/auth": "^2.0.6",
    "@adonisjs/fold": "^4.0.4",
    "adonis-ace": "^3.0.8",
    "adonis-auth": "^1.0.7",
    "adonis-cli": "^2.1.9",
    "adonis-commands": "^2.1.5",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.14",
    "adonis-lucid": "^3.0.16",
    "adonis-middleware": "^1.0.14",
    "adonis-redis": "^1.0.1",
    "adonis-validation-provider": "^3.0.5",
    "adonis-websocket": "^1.0.4",
    "adonis-websocket-client": "^1.0.2",
    "crypto": "0.0.3",
    "fs": "0.0.1-security",
    "jquery": "^3.2.1",
    "mssql": "^4.1.0",
    "mysql": "^2.14.1",
    "pify": "^3.0.0",
    "request": "^2.83.0",
    "solc": "^0.4.17",
    "ua-parser-js": "^0.7.14",
    "uikit": "^3.0.0-beta.30",
    "web3": "^0.19.1",
    "youch": "^2.0.5"
  }

please help me out here! its been bugging me for hours...

**Comment by thetutlage** [comment]
It’s happening coz u r mixing 4.0 n 3.2 dependencies together

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
