### ISSUE TITLE
[i18n - v4] TypeError: HttpContext.onReady is not a function

### ISSUE THREAD

**Issue by danilopolani** [adonisjs/adonis-framework#694]
### Brief Description
I'm trying to use the i18n package in order to translate the site in multiple languages. When I run `npm run dev`, the script throws an error.

### Sample Code
1. Follow the instructions here
2. Create the path `resources/locales/en/homepage.json`
3. Put this content in homepage: 
```
{
  "subtitle": "Hello world!"
}
```
4. In `welcome.edge`, write `{{ antl.formatMessage('homepage.subtitle') }}`

### Error Stack (if any)
```
TypeError: HttpContext.onReady is not a function
    at module.exports (/var/www/project/node_modules/@adonisjs/antl/src/ContextBindings/index.js:45:15)
    at AntlProvider.boot (/var/www/project/node_modules/@adonisjs/antl/providers/AntlProvider.js:86:38)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by thetutlage** [comment]
Make sure you are on the latest version of all packages. 

```
rm -rf node_modules
rm package-lock.json
npm i
```

**Comment by danilopolani** [comment]
Thank you, since I'm using yarn, I just ran `yarn upgrade --latest` and now it works.
