### ISSUE TITLE
Have a error in Validator

### ISSUE THREAD

**Issue by mrtranquanghieu** [adonisjs/adonis-framework#696]
This example doesn't work by error in SQL syntax
(https://dev.adonisjs.com/docs/4.0/validator#_validating_user_input)
`2017-11-04T15:42:25.232Z - info: serving app on http://127.0.0.1:3333
[ { field: 'email',
    validation: 'unique',
    message:
     { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version
for the right syntax to use near 'where `email` = 'mrtranquanghieu@gmail.com'' at line 1
    at Query.Sequence._packetToError (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
    at Protocol._enqueue (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (F:\SourceCode\AdonisJS\adonis4.0\node_modules\mysql\lib\Connection.js:208:25)
    at F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Runner.run (F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (F:\SourceCode\AdonisJS\adonis4.0\node_modules\knex\lib\interface.js:35:43)
    at Promise (F:\SourceCode\AdonisJS\adonis4.0\node_modules\@adonisjs\lucid\src\Validator\index.js:76:10)
    at Promise (<anonymous>)
    at ValidatorRules.unique (F:\SourceCode\AdonisJS\adonis4.0\node_modules\@adonisjs\lucid\src\Validator\index.js:46:12)
    at Promise (F:\SourceCode\AdonisJS\adonis4.0\node_modules\indicative\src\Validator\engine.js:54:5)
    at Promise (<anonymous>)
    at Object.ValidationEngine.runValidationOnField (F:\SourceCode\AdonisJS\adonis4.0\node_modules\indicative\src\Validator\engine.js
:53:10)
    at _.map (F:\SourceCode\AdonisJS\adonis4.0\node_modules\indicative\src\Validator\engine.js:33:29)
    at arrayMap (F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:660:23)
    at Function.map (F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:9571:14)
    at Object.ValidationEngine.validateField (F:\SourceCode\AdonisJS\adonis4.0\node_modules\indicative\src\Validator\engine.js:32:28)
    at _.map (F:\SourceCode\AdonisJS\adonis4.0\node_modules\indicative\src\Validator\index.js:33:64)
    at F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:3554:27
    at F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:3001:24)
    at F:\SourceCode\AdonisJS\adonis4.0\node_modules\lodash\lodash.js:4913:18
       code: 'ER_PARSE_ERROR',
       errno: 1064,
       sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'
where `email` = \'mrtranquanghieu@gmail.com\'\' at line 1',
       sqlState: '42000',
       index: 0,
       sql: 'select * where `email` = \'mrtranquanghieu@gmail.com\'' } } ]`

I think missing the where clause in the query

**Comment by BuiHuyCuong** [comment]
I think you should edit rules:   email : 'required|email|unique' into 'required|email|unique:table_name'.

**Comment by mrtranquanghieu** [comment]
@BuiHuyCuong: Tks Bro. I solved the problem
