### ISSUE TITLE
Allow route validators to be applied to resourceful routes

### ISSUE THREAD

**Issue by watzon** [adonisjs/adonis-framework#701]
## Structuring The Issue
Route validators are a really cool addition to Adonis, but it doesn't look like they currently work with resourceful routes. It would be cool if we could apply a validator to a `Route.resource` instance and have the Validator and Serializer automatically applied to all of the routes.

### Sample Code

```js
Route.resource('users', 'UsersController')
          .validator('User')
```

### Error Stack

```
TypeError: Cannot read property 'middleware' of undefined
    at _.castArray.reduce.forEach (/home/watzon/.../node_modules/@adonisjs/framework/src/Route/Resource.js:279:35)
    at Array.forEach (<anonymous>)
    at RouteResource.middleware (/home/watzon/.../node_modules/@adonisjs/framework/src/Route/Resource.js:278:10)
    at RouteResource.validator (/home/watzon/.../node_modules/@adonisjs/validator/providers/ValidatorProvider.js:116:12)
    at Route.group (/home/watzon/.../start/routes.js:21:11)
    at RouteManager.group (/home/watzon/.../node_modules/@adonisjs/framework/src/Route/Manager.js:341:5)
    at Object.<anonymous> (/home/watzon/.../start/routes.js:18:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _preLoadFiles.forEach (/home/watzon/.../node_modules/@adonisjs/ignitor/src/Ignitor/index.js:369:9)
    at Array.forEach (<anonymous>)

    at Array.forEach (<anonymous>)

```

Using Adonis 4.0.0

**Comment by watzon** [comment]
Actually just realized I'm in the wrong place
