### ISSUE TITLE
Issue with adonis new project

### ISSUE THREAD

**Issue by pirmax** [adonisjs/adonis-framework#710]
I have an issue when I create a new project with adonis command.

> adonis new api-test

```
maxence@maxence-optiplex-3010:~/code$ adonis --help
/usr/lib/node_modules/@adonisjs/cli/src/Commands/New/index.js:114
  async handle ({ name }, options) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@adonisjs/cli/src/Commands/index.js:18:8)
maxence@maxence-optiplex-3010:~/code$
```

**Comment by RomainLanz** [comment]
Hey @pirmax! 👋 

It seems that you are using an old version of Node.js
Note that Adonis 4.0 need to have version 8 or greater of Node.js.

**Comment by pirmax** [comment]
@RomainLanz Thanks, I check that this night :)

**Comment by theabhinavdas** [comment]
Thanks @RomainLanz. Faced same issue, upgraded Node.js and it works great now.
