### ISSUE TITLE
Adonis error

### ISSUE THREAD

**Issue by NikolaBarisic** [adonisjs/adonis-framework#754]
When i run adonis serve i get this error

/usr/local/lib/node_modules/@adonisjs/cli/index.js:37
    throw error
    ^

TypeError: Cannot read property 'name' of undefined
    at _.transform (/Users/ivanbarisic/Desktop/Projects/***/node_modules/@adonisjs/ace/src/Command/index.js:522:31)
    at /Users/ivanbarisic/Desktop/Projects/****/node_modules/lodash/lodash.js:13784:16
    at arrayEach (/Users/ivanbarisic/Desktop/Projects/****/node_modules/lodash/lodash.js:537:11)
    at Function.transform (/Users/ivanbarisic/Desktop/Projects/****/node_modules/lodash/lodash.js:13783:43)
    at Function.commanderAction (/Users/ivanbarisic/Desktop/Projects/****/node_modules/@adonisjs/ace/src/Command/index.js:521:20)
    at Command.listener (/Users/ivanbarisic/Desktop/Projects/****/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:159:13)
    at Command.parseArgs (/Users/ivanbarisic/Desktop/Projects/****/node_modules/commander/index.js:653:12)
    at Command.parse (/Users/ivanbarisic/Desktop/Projects/****/node_modules/commander/index.js:475:21)
    at Kernel.invoke (/Users/ivanbarisic/Desktop/Projects/****/node_modules/@adonisjs/ace/src/Kernel/index.js:285:15)

**Comment by thetutlage** [comment]
Can u share more info?

1. Node.js version
2. Operating system
3. And can you run server using `node server.js`?

**Comment by NikolaBarisic** [comment]
Node.js version is v8.9.1, operating system is os x el capitan v10.11.6. Yes i can run server

**Comment by thetutlage** [comment]
Would you mind update `@adonisjs/cli` package by running `npm i -g @adonisjs/cli@latest`?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by AbdelkhalekESI** [comment]
I have the samed issue when deploying adonis app to heroku

**Comment by RaphaelJansson** [comment]
I have the same problem
but when i run 
> node server.js
it works

i want know why?

**Comment by veronesecoms** [comment]
> I have the samed issue when deploying adonis app to heroku

i too, any solution?
