### ISSUE TITLE
User.ApiTokens is not a function error

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#755]
I'm trying to generate a token when logging in, using `request.auth.generate(user)`, but I'm facing the error said in the title.

My `User`:

```javascript
class User extends Lucid {
  apiTokens() {
    return this.hasMany('App/Model/Token');
  }
  ...
}
```

`Token`:

```javascript
class Token extends Lucid {
  user() {
    return this.belongsTo('App/Model/User')
  }
}
```
And here's the code:

```javascript
* accessToken(request, response) {
  const authOperation = new AuthOperation()

  authOperation.email = request.input('email')
  authOperation.password = request.input('password')

  let user = yield authOperation.accessToken()

  if (user === false) {
    let error = authOperation.getFirstError()

    throw new HttpException(error.message, error.code)
  }

  let token = yield request.auth.generate(user);

  response.send({
    user,
    token: token.token
  })
}
```
The console:

```
TypeError: user.apiTokens is not a function
    at LucidSerializer.saveToken (/home/gabriel/Sites/co-report/api/node_modules/adonis-auth/src/Serializers/Lucid/index.js:169:32)
    at saveToken.next (<anonymous>)
    at onFulfilled (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:65:19)
    at /home/gabriel/Sites/co-report/api/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:50:10)
    at toPromise (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:118:63)
    at next (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:99:29)
    at onFulfilled (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:69:7)
    at /home/gabriel/Sites/co-report/api/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:50:10)
    at toPromise (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:118:63)
    at next (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:99:29)
    at onFulfilled (/home/gabriel/Sites/co-report/api/node_modules/co/index.js:69:7)
    at <anonymous>
(node:7197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
```

**Comment by thetutlage** [comment]
What does `authOperation.accessToken` returns?

**Comment by mfgabriel92** [comment]
It returns a User.

Within the code, I look for a User with the e-mail entered

```javascript
const user = yield User.query().where('email', this.email).with(...);
...
return user
```

**Comment by thetutlage** [comment]
Within your code you are checking if `user === false`. The value of user will never be false it will be `null`. So better write a simple if condition.

```js
if (!user) {
  let error = authOperation.getFirstError()
  throw new HttpException(error.message, error.code)
}
```

**Comment by mfgabriel92** [comment]
Unfortunately it didn't solve. The user is not `null`, so it will not execute the code within the condition. It is really weird because I have based this code from another, and it works.

**Comment by thetutlage** [comment]
Can u share the output of `user` variable?

**Comment by mfgabriel92** [comment]
Yes, it is the following, by logging `user` from `accessToken()`:

```
LodashWrapper {
  __wrapped__: 
   [ { id: 1,
       firstName: 'Foo',
       middleName: '',
       lastName: 'Business',
       email: 'foo@business.com',
       type: 'business',
       imageUrl: '',
       address: null,
       mobileNumber: null,
       phoneNumber: null,
       created_at: 2018-01-12T08:35:14.000Z,
       updated_at: 2018-01-12T08:35:14.000Z } ],
  __actions__: 
   [ { func: [Function: transform],
       args: [Object],
       thisArg: [Object] } ],
  __chain__: false,
  __index__: 0,
  __values__: undefined }
```

**Comment by thetutlage** [comment]
What you get is an array of users and not instance of a single user. I recommend calling `.first` at the end of the query chain, to pull a single user instance.

Also is there any specific reason you are using 3.x over 4.0?

**Comment by mfgabriel92** [comment]
It worked, thank you.

There is. The project is much older than the version 4.0.

**Comment by mfgabriel92** [comment]
I was trying to use `request.auth.getUser` but it does not work after this fix.
