### ISSUE TITLE
when loading local service provider adonis cannot start

### ISSUE THREAD

**Issue by rbartholomay** [adonisjs/adonis-framework#77]
Hi,

when try to add a local service provide described here:

[Serviceprovider](http://adonisjs.com/docs/2.0/service-providers#creating-service-providers)

**providers/Hello/Hello.js**

```
class Hello {

  constructor (Config) {
    this.locale = Config.get('app.locale')
  }

  greet () {
    switch (this.locale) {
      case 'fr':
        return 'Bonjour le monde'
      case 'es':
        return 'Hola Mundo'
      default:
        return 'Hello world'
    }
  }
}

module.exports = Hello
```

**providers/Hello/HelloProvider.js**

```
const ServiceProvider = require('adonis-fold').ServiceProvider

class HelloProvider extends ServiceProvider {

  * register () {
    this.app.bind('App/Hello', function (app) {
      const Hello = require('./Hello')
      const Config = app.use('Config')
      return new Hello(Config)
    })
  }
}

module.exports = HelloProvider
```

And add this to *bootstrap/app.js*

```
const path = require('path');
```

```
const providers = [
  path.join(__dirname,'../providers/Hello/HelloProvider.js')
]
```

it results in an error on startup:

```
> node --harmony_proxies server.js

/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/require-stack/src/index.js:57
    const errorsArray = errors.toString().split("\n")
                              ^

TypeError: Cannot read property 'toString' of undefined
    at requireStack (/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/require-stack/src/index.js:57:31)
    at /Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/adonis-fold/src/Registrar/index.js:26:20
    at arrayMap (/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/lodash/index.js:6710:14)
    at Object.Registrar.require (/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/adonis-fold/src/Registrar/index.js:25:12)
    at Object.Registrar.register (/Users/renebartholomay/Sourcen/Concierge3_ad/node_modules/adonis-fold/src/Registrar/index.js:41:32)
    at module.exports (/Users/renebartholomay/Sourcen/Concierge3_ad/bootstrap/http.js:22:6)
    at Object.<anonymous> (/Users/renebartholomay/Sourcen/Concierge3_ad/server.js:13:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

**Comment by thetutlage** [comment]
`let, const, classes` all are allowed in strict mode. So make sure to add it on the top of your file. I know errors are not helpful. But syntax errors get invisible inside the v8 stack, so i am working to find some workaround it.
