### ISSUE TITLE
Can't register a `Request.macro` from `Provider`?

### ISSUE THREAD

**Issue by feryardiant** [adonisjs/adonis-framework#807]
## Brief

As mentioned [here](http://adonisjs.com/docs/4.1/request#_extending_request) I am trying to normalize some keys from querystring in purpose for easier data filtering on the Model but I got an error from inside `macro` closure.

From the error stack below, I'm pretty sure that it's happened because `this` inside the closure doesn't actually got instance of `Request`, am I right? But, the inspection tell me otherwise. 😕 

Not sure if it was a bug but it bother me so bad 😅 

- Why is this could happened?
- Where is the best place to register `Request.macro`?

### Sample Code

```js
// ~/app/Models/SomeModel.js
class SomeModel extends Model {
  static scopeFilters (query, filters) {
    for (const load of (filters.with)) {
      query.with(relation)
    }

    // some other stuffs

    return query
  }
}
```
```js
// ~/app/Controllers/Http/SomeController.js (usage)
class SomeController {
  async index ({ request }) {
    const filters = request.filters()

    filters.includes('brand', 'category')

    const method = filters.page > 0 ? 'paginate' : 'fetch'

    const model = await Model.query()
      .filters(filters)[method](filters.page)

    return model
  }
}
```

```js
// ~/providers/Base/Provider.js
class BaseProvider extends ServiceProvider {
  register () {
    const Request = this.app.use('Adonis/Src/Request')

    Request.macro('filters', () => {
      const query = this.get()

      return {
        with: query.with || [],
        page: query.page > 0 ? query.page : 0,
        sort: query.sort ? sanitize(query.sort) : {},
        search: query.search ? sanitize(query.search) : {},
        includes (...params) {
          this.with = query.includes || params
        }
      }
    })
  }
}
```

### Error Stack (if any)

```
TypeError: this.get is not a function
    at Request.macro [as filters] ([d:\Workspaces\personal\codes\adonan]\providers\Base\Provider.js:24:27)
    at ItemsController.index ([d:\Workspaces\personal\codes\adonan]\app\Controllers\Http\ItemsController.js:7:30)
    at Server._routeHandler ([d:\Workspaces\personal\codes\adonan]\node_modules\@adonisjs\framework\src\Server\index.js:326:32)
    at Server._resolveMiddleware ([d:\Workspaces\personal\codes\adonan]\node_modules\@adonisjs\framework\src\Server\index.js:216:29)
    at Runnable._invoke ([d:\Workspaces\personal\codes\adonan]\node_modules\co-compose\src\Runnable.js:76:43)
    at once ([d:\Workspaces\personal\codes\adonan]\node_modules\co-compose\src\Runnable.js:73:35)
    at f ([d:\Workspaces\personal\codes\adonan]\node_modules\once\once.js:25:26)
    at Auth.handle ([d:\Workspaces\personal\codes\adonan]\node_modules\@adonisjs\auth\src\Middleware\Auth.js:113:12)
    at <anonymous>
```

### Screenshots

![image](https://user-images.githubusercontent.com/508665/37256771-fde395ba-2591-11e8-8e71-04a31d521448.png)

Thanks & regards.
Sorry for my bad english 🥂

**Comment by RomainLanz** [comment]
Hey @feryardiant! 👋 

Since you are using an arrow function you are sharing the scope of the parent.
Use a normal function and everything should be fine.

**Comment by feryardiant** [comment]
Thanks for quick reply @RomainLanz and yes you're right.

Seem's I have to reopen [this book](https://www.ebooks.com/1647631/you-don-t-know-js-scope-closures/simpson-kyle/) tho 😅
