### ISSUE TITLE
Getting error with adonis new yardstick 

### ISSUE THREAD

**Issue by deveshsinghal22** [adonisjs/adonis-framework#81]
```
/usr/local/lib/node_modules/adonis-cli/index.js:10
const argv = require('yargs').argv
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3


```

**Comment by deveshsinghal22** [comment]
Seems this is because I am using nodeJs version 0.10.x

**Comment by thetutlage** [comment]
yes, adonis needs >4.0

**Comment by RomainLanz** [comment]
We require `node >= 4.0` and `npm >= 3.0`.

**Comment by deveshsinghal22** [comment]
ok. 
Thanks for update @thetutlage @RomainLanz  :)
