### ISSUE TITLE
adonis --help | Error

### ISSUE THREAD

**Issue by ichekh** [adonisjs/adonis-framework#841]
Command:
>_ adonis --help
Result:
async _setupProjectDirectory (stepsCounter, appPath, options) {
        ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ich50200\AppData\Roaming\npm\node_modules\@adonisjs\cli\src\Commands\index.js:18:8)

**Comment by webdevian** [comment]
What version of node are you using? It looks like your version doesn’t support Async/Await

**Comment by ichekh** [comment]
current version of node is 7, i try the update version of node to 9, now is good working.

Thanks
