### ISSUE TITLE
auth.generateForRefreshToken() not working correctly

### ISSUE THREAD

**Issue by alexechdev** [adonisjs/adonis-framework#867]
## AuthController
```json
refreshToken: 19eb1d66784ce54a6564ed98aff95bdb/AJ8Zh4w6sVwwDmPvacKHEf3o4g6qx+PXVuuK6+6j5SK0gOUZdBFTJpuhNJoSKnD
```

```javascript
await auth
    .newRefreshToken()
    .generateForRefreshToken(refreshToken)
```
## Error

```javascript
{ Error: Unknown column 'users.id' in 'where clause'
    at Packet.asError (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
From previous event:
    at Client_MySQL2._query (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL2.query (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/runner.js:61:21
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Runner.run (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (/Users/alexech/Desarrollo/Freelance/Evrpets/System/webservice/node_modules/knex/lib/interface.js:39:43)
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: 'Unknown column \'users.id\' in \'where clause\'' }

```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
