### ISSUE TITLE
error run migration in mysql

### ISSUE THREAD

**Issue by xabree** [adonisjs/adonis-framework#916]
error run migration in mysql when create table adonis_schema.

```
 Error: ER_INVALID_DEFAULT: Invalid default value for 'migration_time'
    at Query.Sequence._packetToError (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
    --------------------
    at Protocol._enqueue (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/mmakmur/adonis-cms/node_modules/mysql/lib/Connection.js:200:25)
    at /Users/mmakmur/adonis-cms/node_modules/knex/lib/dialects/mysql/index.js:154:18
    at Promise._execute (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/Users/mmakmur/adonis-cms/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/Users/mmakmur/adonis-cms/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/Users/mmakmur/adonis-cms/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/Users/mmakmur/adonis-cms/node_modules/knex/lib/runner.js:212:40)
    at /Users/mmakmur/adonis-cms/node_modules/knex/lib/runner.js:46:23
    at tryCatcher (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Users/mmakmur/adonis-cms/node_modules/bluebird/js/release/util.js:16:23)
  code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sqlMessage: 'Invalid default value for \'migration_time\'',
  sqlState: '42000',
  index: 0,
  sql: 'create table `adonis_schema` (`id` int unsigned not null auto_increment primary key, `name` varchar(255), `batch` int, `migration_time` timestamp default CURRENT_TIMESTAMP(6))' }
```

package.json
```
"adonis-version": "4.1.0",

dependencies": {
    "@adonisjs/ace": "^5.0.3",
    "@adonisjs/auth": "^3.0.6",
    "@adonisjs/bodyparser": "^2.0.4",
    "@adonisjs/cors": "^1.0.6",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.8",
    "@adonisjs/ignitor": "^2.0.7",
    "@adonisjs/lucid": "^6.0.0",
    "@adonisjs/session": "^1.0.26",
    "@adonisjs/shield": "^1.0.7",
    "mysql": "^2.16.0"
  },
  "devDependencies": {},
  "autoload": {
    "App": "./app"
  }
}

```

spesific error
```
create table `adonis_schema` (
    `id` int unsigned not null auto_increment primary key, 
    `name` varchar(255), `batch` int, 
    `migration_time` timestamp default CURRENT_TIMESTAMP(6)
)
```

I think CURRENT_TIMESTAMP(6) cause the error, when i use only CURRENT_TIMESTAMP it works

**Comment by RomainLanz** [comment]
Hey @xabree! 👋 

Which version of MySQL are you using?

**Comment by thetutlage** [comment]
Yeah, this happened after Knex added support for [precision](https://github.com/tgriesser/knex/issues/2715) timestamps in MYSQL. I added a hacky fix for time being, but seems like knex has [pushed a fix](https://github.com/tgriesser/knex/commit/4fd16da45ae6b66c8e5a3fa447294c3009723dff) too. Lemme publish a new release which fixes this.

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonis-lucid/commit/f5a6b331b4be6d0138ced16c6de7ef2640a89d88
