### ISSUE TITLE
Deploying on heroku not working

### ISSUE THREAD

**Issue by egodasa** [adonisjs/adonis-framework#980]
The log show `serving app on http://null:38053` and the app just show "Heroku | Welcome to your new app!
". I'm trying to set HOST variable inside heroku vars. Change it to `127.0.0.1` still gave me same result. 

Changet it to the app url, the log shows error :
```
remote: > adonis-fullstack-app@4.1.0 start /app
remote: > node server.js
remote: 
remote: info: serving app on http://crud-peta.herokuapp.com:59971
remote: events.js:183
remote:       throw er; // Unhandled 'error' event
remote:       ^
remote: 
remote: Error: listen EADDRNOTAVAIL 34.251.216.39:59971
remote:     at Object._errnoException (util.js:1022:11)
remote:     at _exceptionWithHostPort (util.js:1044:20)
remote:     at Server.setupListenHandle [as _listen2] (net.js:1334:19)
remote:     at listenInCluster (net.js:1392:12)
remote:     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
remote:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! adonis-fullstack-app@4.1.0 start: `node server.js`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the adonis-fullstack-app@4.1.0 start script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2018-10-17T16_39_13_233Z-debug.log
remote: Waiting for release.... failed.
```

And this is the log access :
```
2018-10-17T16:13:20.138313+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=crud-peta.herokuapp.com request_id=570578fd-a44a-49e8-a8ef-052527727f73 fwd="203.78.120.39" dyno= connect= service= status=502 bytes= protocol=http
2018-10-17T16:13:21.156489+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=crud-peta.herokuapp.com request_id=4e9f3d02-c61a-4a7d-b7a7-a497b50f88de fwd="203.78.120.39" dyno= connect= service= status=502 bytes= protocol=http
```
I ever deploy nodejs app with expressjs before on heroku and it still running.
I'm try to use google,adonis forum and search issues but no luck.
The app run on local machine. Thanks.

**Comment by thetutlage** [comment]
`HOST` can never be the app URL and have to allow all hosts when deploying on heroku. 

Set `HOST=0.0.0.0` and it should work

**Comment by egodasa** [comment]
I'm sorry. But still no luck. This is the full log (no error) :
```
mandan@mandan-pc:~/yardstick$ git push heroku psql:master
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 351 bytes | 351.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=development
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.9.4
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 8.9.4...
remote:        Downloading and installing node 8.9.4...
remote:        Using default npm version: 5.6.0
remote:        
remote: -----> Restoring cache
remote:        - node_modules
remote:        
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        up to date in 3.24s
remote:        
remote: -----> Caching build
remote:        - node_modules
remote:        
remote: -----> Pruning devDependencies
remote:        Skipping because NODE_ENV is not 'production'
remote:        
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> release, web
remote: 
remote: -----> Compressing...
remote:        Done: 24M
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v24
remote:        https://crud-peta.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
remote: Running release command...
remote: 
remote: 
remote: > adonis-fullstack-app@4.1.0 start /app
remote: > node server.js
remote: 
remote: info: serving app on http://0.0.0.0:14457
^C
mandan@mandan-pc:~/yardstick$ heroku plugins:install heroku-releases-retry
 ›   Warning: heroku update available from 7.7.8 to 7.14.4
Installing plugin heroku-releases-retry... installed v1.0.3
mandan@mandan-pc:~/yardstick$ heroku releases:retry --app crud-peta
 ›   Warning: heroku update available from 7.7.8 to 7.14.4
Retrying v25 on ⬢ crud-peta... done, v26
 ▸    Release command declared: this new release will not be available until the command succeeds.
Running release command...

> adonis-fullstack-app@4.1.0 start /app
> node server.js

info: serving app on http://0.0.0.0:36745

```
![heroku](https://user-images.githubusercontent.com/9961837/47134628-98504880-d2d7-11e8-8f2b-dae1c5c9aead.png)
This is my app. Looks like node instance not run. I don't know is this problem come from heroku or from my app.
